const steps = {
  0: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Luctus venenatis lectus magna fringilla urna porttitor. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Scelerisque in dictum non consectetur a erat nam at. Consequat interdum varius sit amet. Mus mauris vitae ultricies leo integer malesuada. Aenean vel elit scelerisque mauris. Vitae et leo duis ut diam quam nulla porttitor. Feugiat pretium nibh ipsum consequat. Senectus et netus et malesuada fames ac turpis. Enim ut sem viverra aliquet eget sit amet. Tellus orci ac auctor augue mauris augue neque gravida. Faucibus scelerisque eleifend donec pretium vulputate sapien nec.',
  1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Luctus venenatis lectus magna fringilla urna porttitor. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Scelerisque in dictum non consectetur a erat nam at. Consequat interdum varius sit amet. Mus mauris vitae ultricies leo integer malesuada. Aenean vel elit scelerisque mauris. Vitae et leo duis ut diam quam nulla porttitor. Feugiat pretium nibh ipsum consequat. Senectus et netus et malesuada fames ac turpis. Enim ut sem viverra aliquet eget sit amet. Tellus orci ac auctor augue mauris augue neque gravida. Faucibus scelerisque eleifend donec pretium vulputate sapien nec.',
  2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Luctus venenatis lectus magna fringilla urna porttitor. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Scelerisque in dictum non consectetur a erat nam at. Consequat interdum varius sit amet. Mus mauris vitae ultricies leo integer malesuada. Aenean vel elit scelerisque mauris. Vitae et leo duis ut diam quam nulla porttitor. Feugiat pretium nibh ipsum consequat. Senectus et netus et malesuada fames ac turpis. Enim ut sem viverra aliquet eget sit amet. Tellus orci ac auctor augue mauris augue neque gravida. Faucibus scelerisque eleifend donec pretium vulputate sapien nec.',
  3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Luctus venenatis lectus magna fringilla urna porttitor. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Scelerisque in dictum non consectetur a erat nam at. Consequat interdum varius sit amet. Mus mauris vitae ultricies leo integer malesuada. Aenean vel elit scelerisque mauris. Vitae et leo duis ut diam quam nulla porttitor. Feugiat pretium nibh ipsum consequat. Senectus et netus et malesuada fames ac turpis. Enim ut sem viverra aliquet eget sit amet. Tellus orci ac auctor augue mauris augue neque gravida. Faucibus scelerisque eleifend donec pretium vulputate sapien nec.',
  4: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Luctus venenatis lectus magna fringilla urna porttitor. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Scelerisque in dictum non consectetur a erat nam at. Consequat interdum varius sit amet. Mus mauris vitae ultricies leo integer malesuada. Aenean vel elit scelerisque mauris. Vitae et leo duis ut diam quam nulla porttitor. Feugiat pretium nibh ipsum consequat. Senectus et netus et malesuada fames ac turpis. Enim ut sem viverra aliquet eget sit amet. Tellus orci ac auctor augue mauris augue neque gravida. Faucibus scelerisque eleifend donec pretium vulputate sapien nec.'
}

export default steps
